# Generated by Django 5.0.14 on 2026-05-17 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('view_menu', 'View menu'), ('call_restaurant', 'Call restaurant'), ('get_directions', 'Get directions'), ('claim_offer', 'Claim offer'), ('order_uber_eats', 'Order on Uber Eats'), ('order_deliveroo', 'Order on Deliveroo'), ('order_just_eat', 'Order on Just Eat'), ('order_directly', 'Order directly')], max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
