# Generated by Django 5.0.14 on 2026-05-17 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_initial'),
        ('restaurants', '0003_restaurantopeninghour_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationSearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(blank=True, max_length=255)),
                ('postcode', models.CharField(blank=True, max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_search_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RestaurantAnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('view_menu', 'View menu'), ('call_restaurant', 'Call restaurant'), ('get_directions', 'Get directions'), ('claim_offer', 'Claim offer'), ('order_uber_eats', 'Order on Uber Eats'), ('order_deliveroo', 'Order on Deliveroo'), ('order_just_eat', 'Order on Just Eat'), ('order_directly', 'Order directly')], max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurant_analytics_events', to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to='restaurants.restaurant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='AnalyticsEvent',
        ),
        migrations.AddIndex(
            model_name='locationsearchlog',
            index=models.Index(fields=['postcode', 'created_at'], name='analytics_l_postcod_07fb7d_idx'),
        ),
        migrations.AddIndex(
            model_name='locationsearchlog',
            index=models.Index(fields=['customer', 'created_at'], name='analytics_l_custome_d3e689_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurantanalyticsevent',
            index=models.Index(fields=['event_type', 'created_at'], name='analytics_r_event_t_54e991_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurantanalyticsevent',
            index=models.Index(fields=['restaurant', 'created_at'], name='analytics_r_restaur_2a6ca1_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurantanalyticsevent',
            index=models.Index(fields=['customer', 'created_at'], name='analytics_r_custome_14a84e_idx'),
        ),
    ]
