# Generated by Django 5.0.14 on 2026-05-17 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_locationsearchlog_restaurantanalyticsevent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantanalyticsevent',
            name='event_type',
            field=models.CharField(choices=[('profile_view', 'Profile view'), ('menu_view', 'Menu view'), ('offer_claim_click', 'Offer claim click'), ('call_click', 'Call click'), ('direction_click', 'Direction click'), ('favourite_save', 'Favourite save'), ('order_uber_eats_click', 'Order Uber Eats click'), ('order_deliveroo_click', 'Order Deliveroo click'), ('order_just_eat_click', 'Order Just Eat click'), ('order_direct_click', 'Order direct click')], max_length=64),
        ),
    ]
