# Generated by Django 5.0.14 on 2026-05-17 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favourites', '0002_initial'),
        ('restaurants', '0003_restaurantopeninghour_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FavouriteRestaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites', to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourited_by', to='restaurants.restaurant')),
            ],
        ),
        migrations.DeleteModel(
            name='Favourite',
        ),
        migrations.AddIndex(
            model_name='favouriterestaurant',
            index=models.Index(fields=['customer', 'created_at'], name='favourites__custome_9d400a_idx'),
        ),
        migrations.AddConstraint(
            model_name='favouriterestaurant',
            constraint=models.UniqueConstraint(fields=('customer', 'restaurant'), name='unique_favourite_per_customer_restaurant'),
        ),
    ]
