# Generated by Django 5.0.14 on 2026-05-17 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('phone_number', models.CharField(blank=True, max_length=40)),
                ('website_url', models.URLField(blank=True)),
                ('direct_order_url', models.URLField(blank=True)),
                ('uber_eats_url', models.URLField(blank=True)),
                ('deliveroo_url', models.URLField(blank=True)),
                ('just_eat_url', models.URLField(blank=True)),
                ('is_phone_order_available', models.BooleanField(default=False)),
                ('is_collection_available', models.BooleanField(default=False)),
                ('is_delivery_available', models.BooleanField(default=False)),
                ('approval_status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='restaurants', to='locations.location')),
            ],
        ),
    ]
