# Generated by Django 5.0.14 on 2026-05-17 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=120)),
                ('city', models.CharField(max_length=120)),
                ('area', models.CharField(blank=True, max_length=120)),
                ('borough_or_district', models.CharField(blank=True, max_length=120)),
                ('postcode', models.CharField(blank=True, max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['country', 'city'], name='locations_l_country_857b42_idx'), models.Index(fields=['postcode'], name='locations_l_postcod_bfa840_idx')],
            },
        ),
    ]
