# Generated by Django 5.0.14 on 2026-05-17 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offers', '0001_initial'),
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='restaurants.restaurant'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['restaurant', 'is_active'], name='offers_offe_restaur_c03cbb_idx'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['starts_at', 'ends_at'], name='offers_offe_starts__5adc29_idx'),
        ),
    ]
