# Generated by Django 5.0.14 on 2026-05-17 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_initial'),
        ('restaurants', '0003_restaurantopeninghour_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='offer',
            name='offers_offe_starts__5adc29_idx',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='ends_at',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='starts_at',
        ),
        migrations.AddField(
            model_name='offer',
            name='discount_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offer',
            name='minimum_spend',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='offer_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('fixed_amount', 'Fixed amount'), ('free_item', 'Free item'), ('bundle', 'Bundle')], default='percentage', max_length=32),
        ),
        migrations.AddField(
            model_name='offer',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='terms',
            field=models.TextField(blank=True),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['start_date', 'end_date'], name='offers_offe_start_d_8459ce_idx'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['is_featured', 'is_active'], name='offers_offe_is_feat_6c18c1_idx'),
        ),
    ]
